#Reading DNS Settings
server_list = {
  "server1" => {
      "ip"=>"72.22.0.2",
      "provision"=>{
        "type"=>"shell",
        "path"=>"config_centos.sh"
      },
      "share"=>{
        "from"=>"./shared/",
        "to"=>"/shared"
      }
    },
    "server2" => {
        "ip"=>"72.22.0.3"
    }
}
#collect all hosts
dnsOutput = "";
server_list.each do |hostname, info|
  dnsOutput << "\n#{info["ip"]} #{hostname} #{hostname}"
end
#creating simple script for Hosts update
script = <<SCRIPT
  echo "#{dnsOutput}" >> /etc/hosts
SCRIPT

# VM configs
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #Centos based
  config.vm.box = "centos/7"

  #configure machines
  server_list.each do |dns_name, info|
    config.vm.define dns_name do |server|
      server.vm.hostname = dns_name
      server.vm.network "private_network", ip: info["ip"]
      if info.has_key?("share") then
        server.vm.synced_folder info["share"]["from"], info["share"]["to"]
      end
      if info.has_key?("provision") then
        server.vm.provision info["provision"]["type"], path: info["provision"]["path"]
      end
      server.vm.provision "shell",
        inline: script
    end
  end
end
