VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #Centos based
  config.vm.box = "centos/7"

  #Ubuntu based
  #config.vm.box = "precise64"
  #config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  #Settings for server 1
  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "172.22.0.2"
    server1.vm.synced_folder "./shared/", "/shared"

    #for ubuntu
    #server1.vm.provision "shell", path: "config.sh"

    #for centos
    server1.vm.provision "shell", path: "config_centos.sh"
    #register foreign host name
    server1.vm.provision "shell",
      inline: "echo '172.22.0.3  server2 server2' >> /etc/hosts"
  end

  #Settings for server 2
  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "172.22.0.3"
    #register foreign host name
    server2.vm.provision "shell",
      inline: "echo '172.22.0.2  server1 server1' >> /etc/hosts"
  end
end
